name: Linting

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Python
      uses: actions/setup-python@v5
    - name: Install tox
      run: python -m pip install tox
    - name: Lint
      run: python -m tox -e lint
